### ISSUE TITLE
How to build rewrite branch?

### ISSUE THREAD

**Issue by llamaking136** [Abb1x/example-kernel#34]
Hello,

While trying to build the `rewrite` branch, I came across this error:

```
make: *** No rule to make target `$(ISO)'.   Stop.
```
What should I do? Is there a build script that I should run?
I already have cross-compiling utilities, as listed in the Makefile.

**Comment by rdmsr** [comment]
well that's odd, how did you clone?

**Comment by llamaking136** [comment]
I used Git to clone it. I made sure to use --recursive.

**Comment by rdmsr** [comment]
that's weird

Did you only run `make`?

**Comment by llamaking136** [comment]
Yeah. Should I have built Limine or echfs?

**Comment by rdmsr** [comment]
try doing this: `git clone https://github.com/Abb1x/emerald -b rewrite --recursive && make`

**Comment by llamaking136** [comment]
It still gives me the same problem. I even tried building Limine.

**Comment by rdmsr** [comment]
that is very weird TBH, I don't know what could cause this. Works fine for me

**Comment by llamaking136** [comment]
Oh well. Thanks for trying. I'll update this when I figured it out.

**Comment by llamaking136** [comment]
I finally got it to compile, but I think I may have found more problems.

GCC gave me an error, saying that stdio.h was not found in `log.h`.
I think it's trying to include it because the macro `HOST` is defined.

Do you know why it's checking for `HOST`?

Full error message:

```
-e CC [%] src/lib/emerald/log.c
In file included from src/lib/emerald/log.c:7:
src/lib/emerald/log.h:17:14: fatal error: stdio.h: No such file or directory
   17 | #    include <stdio.h>
      |              ^~~~~~~~~
compilation terminated.
make: *** [build/host/src/lib/emerald/log.c.o] Error 1
```

**Comment by rdmsr** [comment]
That's for linux compilation, the option shouldn't be enabled unless you're running tests or building the library

**Comment by llamaking136** [comment]
What is the library, and should I try building it first?

**Comment by rdmsr** [comment]
The kernel's library, just running make after cloning should work fine. I don't know what's wrong.

**Comment by llamaking136** [comment]
Okay, I've got it compiled. It runs in the emulator, but with a *minor* issue. I'll open a PR for a `build.md` file with instructions to build.
