### ISSUE TITLE
Compile, Issue Here...

### ISSUE THREAD

**Issue by archuser555** [Abb1x/example-kernel#37]
hello, when i compile, i get the folowing... i have 32bit machine runing debian, sorry the folowing text are in frensh so try use gooogle translate, thanks:
make[1]: *** Aucune règle pour fabriquer la cible « limine-install ». Arrêt.
make: *** [Makefile:82 : limine/limine-install] Erreur 2
make[1] : on entre dans le répertoire « /home/archuser555/Bureau/emerald-master/thirdparty/limine »
make[1]: *** Aucune règle pour fabriquer la cible « limine-install ». Arrêt.
make[1] : on quitte le répertoire « /home/archuser555/Bureau/emerald-master/thirdparty/limine »
make: *** [Makefile:82 : limine/limine-install] Erreur 2

i think the folowing issue because i dont have limine, but wait, limine is only a binary file... so just, i want to understand why this go with me

**Comment by llamaking136** [comment]
How did you download the Emerald source code? If you're using `git`, you'll have to re-download it because `make` might not be finding the Limine directory. Make sure to use the `--recurse-submodules` option.

**Comment by llamaking136** [comment]
Was the error fixed?

**Comment by archuser555** [comment]
Yes, Thanks!

**Comment by archuser555** [comment]
I close the issue btw, thanks + WE NEED A OS BASED ON THIS KERNRL BTW
